name: Fetch Active Developer Addresses

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  fetch-devs:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create output folder
        shell: pwsh
        run: |
          mkdir output -Force

      - name: Run dev.ps1 to fetch dev addresses
        shell: pwsh
        run: |
          ./dev.ps1

      - name: Commit and push CSV if changed
        run: |
          git config user.name "ao-stats-bot"
          git config user.email "bot@ao-volume.ai"
          git add output/dev-addresses.csv
          git commit -m "📥 Updated developer address list" || echo "No changes to commit"
          git push
